### ISSUE TITLE
Sample Issue 01

### ISSUE THREAD

**Issue by codejamtc** [topcoder-archive/TCO21-Regionals-QA-Competition#1]
https://user-images.githubusercontent.com/42398485/128153564-e7a898c0-d58a-40a5-bd3d-40c4cd0145d8.mp4

![bandicam 2021-08-04 14-31-18-492](https://user-images.githubusercontent.com/42398485/128153576-10d3589f-d2af-4fe3-b956-de888878a8fe.jpg)

### Target URL
https://www.amazon.com/Dell-ChromeBook-NoteBook-Certified-Refurbished/dp/B07781S5L5/ref=sr_1_3?dchild=1&keywords=Laptop&qid=1628067323&refinements=p_36%3A1000-10000&rnid=2421885011&sr=8-3

### Steps to Reproduce

1. Open the URL https://www.amazon.com/
2. Log in as a valid-user 
3. Select "All' from the dropdown near the search box and Add "Laptop" as the keyword and perform a search
4. From the filter apply Price = $0 - $100 
5. Select the product "Dell ChromeBook 11.6 Inch HD (1366 x 768) Laptop NoteBook PC, Intel Celeron N2840, Camera, HDMI, WIFI, USB 3.0, SD Card Reader (Renewed)"
6. Click on the 'Add to cart' button

### Actual Result(s)

- User can't add the product to the cart

### Expected Result(s)

- User should be able to add the product to the cart and added product should display on the side panel

### Environment Details

- **Device(s):** MacBook Pro 13-Inch
- **Resolution:** 2560×1600
- **Operating System:** macOS Big Sur 11.5.1 (20G80)
- **Browser(s):** Safari 11.xxx

**Comment by sharma-sajal** [comment]
sdsd
