### ISSUE TITLE
entering a text in "How can we help" keeps on loading 

### ISSUE THREAD

**Issue by rprakash20** [topcoder-archive/TCO21-Regionals-QA-Competition#12]
### Steps to Reproduce
1. Open https://kb.newegg.com/ in browser
2. Type in a text in the search field
3. Wait for the result and keep noticing the loading icon
4. Enable browser inspector and look for any errors

### Target URL
https://kb.newegg.com/

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2021-08-04 at 6 38 46 PM" src="https://user-images.githubusercontent.com/5712602/128186771-a367a49a-771f-4692-9ffd-4a2563adc7fe.png">

https://user-images.githubusercontent.com/5712602/128187003-4adba9c5-f3d9-46f2-bb90-e3744aadbaff.mov

### Current Results
entering a text in "How can we help" keeps on loading and never returns any result

### Expected Results
entering a text in "How can we help" should return results and. if there are no matching results should show no match found or similar.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Version 92.0.4515.107 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by rajanmourya** [comment]
https://user-images.githubusercontent.com/42939505/128231945-42344832-77b5-4581-a4a3-1a4dbcc8b5df.mp4

The text field is getting loading continously

**Comment by codejamtc** [comment]
**Submitter**: 0 Points | Similar https://github.com/topcoder-platform/TCO21-Regionals-QA-Competition/issues/7 not the same place but share the same ID and code

```
<input id="hkb-search" class="hkb-site-search__field" type="text" value="" placeholder="Search the knowledge base..." name="s" autocomplete="off">
```

**Challenger**: 0 Points
