### ISSUE TITLE
Test case 1 Execution

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-archive/TCO21-Regionals-QA-Competition#6]
Test Case 01:

Go to https://www.newegg.com/
Click on "Sign In/Register"
Click 'Sign Up'
Enter First name, last name, invalid email address (codejam@mailinator) and add a valid password click 'Sign Up'
Enter valid email address (codejam@mailinator.com) and click 'Sign Up'
Click on the welcome note with the customer name > Account Settings
Click on the welcome note with the customer name > Sign Out

Attached the video

### Environment Details
Device(s): HP
Operating System: Window 10
Browser(s): Chrome Version 92.0.4515.131 (Official Build) (64-bit)

https://user-images.githubusercontent.com/42939505/128186195-67bb970d-d596-4cbe-bd9a-c9ba628635f3.mp4

**Comment by codejamtc** [comment]
@rajanmourya You don't need to report the test cases executions in GitHub. Do it offline and attach the results while you are submitting to the challenge.
